import type { Metadata } from "next";
import { BackgroundLayout } from "@/src/components/features/BackgroundLayout";
import { ThemeToggle } from "@/src/components/ui/ThemeToggle";
import "./globals.css";
import "./leaflet.css";
export const metadata: Metadata = {
  title: "Prueba técnica FE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="w-full">
        <ThemeToggle />
        <BackgroundLayout>
        {children}
        </ BackgroundLayout>
      </body>
    </html>
  );
}
